#!/bin/bash

clear
echo -e "==================================================="
echo -e "#            Autoscript By TukangOprek            #"
echo -e "#-------------------------------------------------#"
echo -e "# For Debian 9 & Debian 10 64 bit                 #"
echo -e "# For Ubuntu 18.04 & Ubuntu 20.04 64 bit          #"
echo -e "# For VPS with KVM and VMWare virtualization      #"
echo -e "# Modded By Vinstechmy                            #"
echo -e "#-------------------------------------------------#"
echo -e "#        THANKS FOR PURCHASE THIS SCRIPTS         #"
echo -e "#-------------------------------------------------#"
echo -e "# TukangOprek Premium Autoscript Lifetime         #"
echo -e "#                                                 #"
echo -e "# Telegram : t.me/TukangOprek                     #"
echo -e "#                                                 #"
echo -e "#-------------------------------------------------#"
echo -e "#         © Copyright 2025 by TukangOprek         #"
echo -e "==================================================="
